/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-on-surface": "#2d3136",
        "surface-container-low": "#181c21",
        "on-secondary-fixed": "#2c0051",
        "surface": "#101419",
        "surface-container-high": "#262a30",
        "on-error": "#690005",
        "surface-bright": "#36393f",
        "on-tertiary-fixed-variant": "#404758",
        "surface-dim": "#101419",
        "on-surface-variant": "#ccc3d8",
        "on-tertiary-container": "#dfe5fa",
        "surface-container-lowest": "#0a0e13",
        "inverse-surface": "#e0e2ea",
        "surface-container": "#1c2025",
        "surface-container-highest": "#31353b",
        "on-primary-container": "#ede0ff",
        "on-secondary": "#490080",
        "secondary": "#ddb7ff",
        "primary-fixed-dim": "#d2bbff",
        "on-tertiary-fixed": "#141b2b",
        "on-tertiary": "#293040",
        "secondary-fixed-dim": "#ddb7ff",
        "secondary-fixed": "#f0dbff",
        "on-primary": "#3f008e",
        "outline": "#958da1",
        "surface-variant": "#31353b",
        "surface-tint": "#d2bbff",
        "inverse-primary": "#732ee4",
        "on-surface": "#e0e2ea",
        "secondary-container": "#6f00be",
        "outline-variant": "#4a4455",
        "primary": "#d2bbff",
        "primary-fixed": "#eaddff",
        "tertiary-container": "#5f6678",
        "tertiary-fixed": "#dce2f7",
        "primary-container": "#7c3aed",
        "on-error-container": "#ffdad6",
        "background": "#101419",
        "on-background": "#e0e2ea",
        "on-secondary-container": "#d6a9ff",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#6900b3",
        "tertiary": "#c0c6db",
        "error-container": "#93000a",
        "on-primary-fixed": "#25005a",
        "tertiary-fixed-dim": "#c0c6db"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "container-padding-desktop": "32px",
        "margin-page": "40px",
        "base": "8px",
        "container-padding-mobile": "16px"
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "12px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
